# Generated by Django 3.2.8 on 2021-11-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=200, unique=True)),
                ('user_password', models.CharField(max_length=200)),
                ('advisors', models.ManyToManyField(to='admin_api.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.advisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
            ],
        ),
    ]
